global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'petcare:8080' ]
        labels:
          application: 'PetCare API'